#!/bin/sh

set -e

# conffile still present, but pi-tryboot removed
if ! which tryboot-install >/dev/null 2>&1; then
	exit 0
fi

abi="${1}"
# ignored
_initrd="${2}"

# Only reinstall the TBE if it exists already
if tryboot-query "${abi}" ; then
	tryboot-install "${abi}"
fi
