#! /bin/sh
set -e

which tryboot-install >/dev/null 2>&1 || exit 0

if type systemd-detect-virt >/dev/null 2>&1 &&
   systemd-detect-virt --quiet --container ; then
	exit 0
fi

version=${1}

if [ -z "${version}" ] ; then
	echo "W: pi-tryboot: Missing kernel version" >&2
	exit 2
fi

# Avoid running multiple times
if [ -n "${DEB_MAINT_PARAMS}" ] ; then
    eval set -- "${DEB_MAINT_PARAMS}"
    if [ -z "${1}" ] || [ "${1}" != "remove" ] ; then
        exit 0
    fi
fi

tryboot-install -r "${version}" >&2 || true
